Add the optional ability to switch directories
mathieudutour/github-tag-action pull request #100
Opened 2021-10-11 23:53 UTC by AlexDCraig

This allows the user to change the directory in which the tagging logic runs.

2021-11-16 17:41 UTC, mathieudutour requested changes
Thanks for the PR! A couple of notes

2021-11-16 17:41 UTC, mathieudutour commented on src/action.ts
> +      console.log('Changed directory from ' + originDirectory + ' to ' + process.cwd());
```suggestion
      core.info(`Changed directory from ${originDirectory} to ${process.cwd()}`);
```

2021-11-16 17:41 UTC, mathieudutour commented on src/action.ts
> +      console.log('Error encountered when changing directory: ' + err);
I think we should fail the workflow if the chdir fails, otherwise it might lead to unexpected behaviors

2021-11-16 17:41 UTC, mathieudutour commented on action.yml
> +    description: "Path relative to $GITHUB_WORKSPACE that contains the cloned repository."
Could you also update the doc in the README (with some info as to when you'd want to do that)?

2022-01-25 04:57 UTC, suyog-fp commented
@AlexDHoffer can you pls fix the code as per @mathieudutour's comments?
I need this feature :D

2026-09-23 10:03 UTC, mathieudutour commented
Thanks! v7 adds working_directory for local Git operations. There’s also a separate repository input for targeting another GitHub repository. Closing this as superseded.

2026-09-23 10:03 UTC, closed without merging